### PR TITLE
refactor: open scripts with a button

### PR DESCRIPTION
**Pull request by gerard-queralt**

### CODE REVIEW

**Review by markmeliaa — COMMENTED** [review]
Instead of opening the scripts with a specific keyboard/mouse input (LALT + Click seems super wacky), why don't we add an "Open Script" button under the "Remove Script" one so it is a lot more intuitive?

**Comment by gerard-queralt** [comment]
Alas, there goes my dream of avoiding this button :_)

**Comment by markmeliaa** [comment]
> Alas, there goes my dream of avoiding this button :_)

Why would you like to avoid this button?

**Comment by gerard-queralt** [comment]
To mimic Unity, and I also think it's better as a concept to be able to open scripts with a double click. It still could be done if we told ImGui to ignore clicks on widgets (buttons, fields...), but it's not a big deal in the grand scheme of things.

**Review by markmeliaa — APPROVED** [review]
Well, I thought the button would look better, but it looks awful in the ComponentScript UI. Anyway, that would be enough for now, if we find a better solution another day we can always change it.

**Review by PaablooCH — APPROVED** [review]

**Pull request merged**
