### PR TITLE
Feat: Allura VFXs

### PR DESCRIPTION
**Pull request by UriMurcia**
To test this use the Gameplay_MiniBoss2_with_allura.axolotl scene
- New VFXs and materials for Allura (**heavy finisher**, **light finisher**, **impact attack** and **jump attack**).
- Fixed bullets falling down and stopping after some distance.

Things to fix:
- Jump attack has the same vfx as Light Finisher, it should be changed in the future.
- Trails do not work, don't know why.
- Allura's heavy attack particles do not play on Start (When activating the object)
- Some particles have problemes with transparencies:

https://github.com/Horizons-Games/Axolotl-Engine/assets/45937802/16c3743b-db40-44c8-897d-461effae575c

### CODE REVIEW

**Comment by AuxPort66** [comment]
You have the emitters in disorder, I put the smoke first and it's always working

**Comment by UriMurcia** [comment]
> You have the emitters in disorder, I put the smoke first and it's always working

True, this way is better, eventhough it doesn't solve the problem 100%, if you take a look now, the cercle emitter sometimes won't be seen.

**Review by markmeliaa — APPROVED** [review]
The new VFXs look really good Uri, congrats!

**Comment by MacXxs** [comment]
Uri, you have to be in play mode to see the trails, the mesh needs to be moving.

**Review by MacXxs — DISMISSED** [review]
What i comented!

**Comment by UriMurcia** [comment]
> What i comented!

Trails are not working on an spawned object, it may be related with my problem

**Comment by UriMurcia** [comment]
> > What i comented!
> 
> Trails are not working on an spawned object, it may be related with my problem

@MacXxs actually, you can try to put one trail component on allura in this branch, just as the video, and it doesn't work

**Comment by MacXxs** [comment]
> > > What i comented!
> > 
> > 
> > Trails are not working on an spawned object, it may be related with my problem
> 
> @MacXxs actually, you can try to put one trail component on allura in this branch, just as the video, and it doesn't work

I

> > > What i comented!
> > 
> > 
> > Trails are not working on an spawned object, it may be related with my problem
> 
> @MacXxs actually, you can try to put one trail component on allura in this branch, just as the video, and it doesn't work

I did the video adding a ComponentTrail to allura in this branch, and for me is working. Maybe you mean something else or i don't catch your meaning.

**Comment by UriMurcia** [comment]
> > > > What i comented!
> > > 
> > > 
> > > Trails are not working on an spawned object, it may be related with my problem
> > 
> > 
> > @MacXxs actually, you can try to put one trail component on allura in this branch, just as the video, and it doesn't work
> 
> I did the video adding a ComponentTrail to allura in this branch, and for me is working. Maybe you mean something else or i don't catch your meaning.

Can you test it on the GameplayMiniboss2_withAllura scene? It's not working for me

**Comment by MacXxs** [comment]
> > > > > What i comented!
> > > > 
> > > > 
> > > > Trails are not working on an spawned object, it may be related with my problem
> > > 
> > > 
> > > @MacXxs actually, you can try to put one trail component on allura in this branch, just as the video, and it doesn't work
> > 
> > 
> > I did the video adding a ComponentTrail to allura in this branch, and for me is working. Maybe you mean something else or i don't catch your meaning.
> 
> Can you test it on the GameplayMiniboss2_withAllura scene? It's not working for me

I'm working now, can we do a call at 18:00 and look at it?

**Comment by markmeliaa** [comment]
Did the trails finally work?

**Comment by AuxPort66** [comment]
This PR will wait until we have particles bugs fixed on develop #733 so we can check it all correctly

**Pull request closed without merging**
