### PR TITLE
feat: improved on implementation of ENGINE mode

### PR DESCRIPTION
**Pull request by gerard-queralt**
Changed flag from GAME to ENGINE, as explained in #865bq6duq. Also removed flag from Globals and instead converted it into a Preprocessor definition, which led to changes in build configurations. Instead of the old Debug and Release, now there is DebugEngine, ReleaseEngine, DebugGame and ReleaseGame

### CODE REVIEW

**Comment by PaablooCH** [comment]
Task linked: [CU-865bq6duq Change flag from GAME to ENGINE](https://app.clickup.com/t/865bq6duq)

**Comment by gerard-queralt** [comment]
In case anyone is curious, as I said the flag is now specified in Visual Studio's Preprocessor, meaning that it's set "automatically". In case you need to change it or remove it (hopefully telling me beforehand), here is how you can access it:
b6fc46a0941beb6fa43f7f7a915e5ed9

**Comment by gerard-queralt** [comment]
Also, I know the Solution Configuration window looks very small after this change. Here's a [link](https://stackoverflow.com/questions/32377568/can-i-change-the-width-of-the-solution-configuration-combobox-in-the-ide) showing how to change it. Sorry for the trouble!

**Review by markmeliaa — APPROVED** [review]
Nice! Thank you for your work Gerard, changes like these are the ones that will polish even more our engine por the possible future users.

**Review by sncarbo — APPROVED** [review]
Good work. It's a good idea to start designing and implementing ´ENGINE´ mode with preprocessor directives. 

Keep an eye on it later because these directives should be used carefully (there are some differences between ´#if´ and ´#ifdef´ that need to be discussed), but I think it's a good job.

**Comment by gerard-queralt** [comment]
Thank you both for your feedback! As agreed with @AuxPort66, I'm going to close this pull request and only merge onto `develop` once ENGINE mode is fully implemented.

**Pull request closed without merging**
