### PR TITLE
Profilers

### PR DESCRIPTION
**Pull request by sncarbo**
Integration concerning the Optick Profiler.

### CODE REVIEW

**Review by PaablooCH — APPROVED** [review]
Nice work Santi

**Review by MacXxs — APPROVED** [review]
Everything OK for me!

**Comment by sncarbo** [comment]
@MacXxs I'm glad, thanks for checking it out!

**Review by gerard-queralt — APPROVED** [review]
Thank you for your work Santi, this will be really useful to have!

**Pull request merged**
