### PR TITLE
fix: Elevator script

### PR DESCRIPTION
**Pull request by OriolSors**
- Solved issue with Player transforms and movement
- Now the elevators are bidirectional
- When the PR #745 is approved, then the Player movement animation will be stopped too

### CODE REVIEW

**Review by markmeliaa — COMMENTED** [review]
Works as intended, but could you make that when the elevator is going up/down, Bix or Allura don't get stuck in the walking animation and instead they stay idle? That would be a great touch.

**Review by markmeliaa — DISMISSED** [review]

**Comment by OriolSors** [comment]
> ~Works as intended, but could you make that when the elevator is going up/down, Bix or Allura don't get stuck in the walking animation and instead they stay idle? That would be a great touch.~ Nvm, I just read the description of the pull request.

jajajajaa yess, it is solved inside de Paralyze function, updated at the other PR

**Review by DADSILVER — CHANGES_REQUESTED** [review]
Good Job, I saw the code fine, but if I enter the elevator with a jump, the character will be trapped forever.

You can change REGISTER_FIELD(bixPrefab, GameObject*) for ModulePlayer to get the player and then pick for here.

https://github.com/Horizons-Games/Axolotl-Engine/assets/14923700/5a0e305e-ded3-42b9-941e-34f8a2956e1c

**Comment by OriolSors** [comment]
> Good Job, I saw the code fine, but if I enter the elevator with a jump, the character will be trapped forever.
> 
> You can change REGISTER_FIELD(bixPrefab, GameObject*) for ModulePlayer to get the player and then pick for here.
> 
>  2023-09-23.16-57-40.mp4

Thanks for noticing! Now, as a temporary solution, you can't enable the elevator while jumping. It's the most easy solution I found. As the elevator is a small place, when you land from jumping you only need to move a bit to enable it

**Review by DADSILVER — DISMISSED** [review]

**Comment by markmeliaa** [comment]
Could you merge cevelop into this branch to see that everything works well, please?

**Comment by OriolSors** [comment]
> Could you merge develop into this branch to check that everything works well, please?

Done!

**Review by markmeliaa — APPROVED** [review]

**Review by Dedado3000 — APPROVED** [review]
Perfect, i don't see any problem in engine play, if you could wait until I test release game today at human hours i will merge this

**Pull request merged**
