### PR TITLE
feat: boss planar reflection, add bix's saber area light, shield changes & fix level 3's reflections

### PR DESCRIPTION
**Pull request by PaablooCH**

### CODE REVIEW

**Review by markmeliaa — APPROVED** [review]

**Review by diegusmejia117 — DISMISSED** [review]
Double shield is intended visual for the VFX of the shield, please do not erase.

**Comment by markmeliaa** [comment]
> Double shield is intended visual for the VFX of the shield, please do not erase.

It looks really weird with the double shield, why not only one shield?

**Comment by diegusmejia117** [comment]
This VFX design was inteded as a double shield to bring more a dynamic visual as the one inside rotates counterclockwise and slower while the outside one rotates clockwise and is faster this  was finalized by the members of the art team and approved by the art team a week ago.

**Comment by markmeliaa** [comment]
@MacXxs please if you are touching scenes let me know, I am doing changes too and we will override one another

**Review by markmeliaa — APPROVED** [review]

**Pull request merged**
