### PR TITLE
feat: add categories in WindowInspector context menu

### PR DESCRIPTION
**Pull request by gerard-queralt**
image

Also cleaned up the code (which was the original idea, as the branch name suggests, but got carried away :P)

### CODE REVIEW

**Comment by gerard-queralt** [comment]
Also taking the opportunity to merge a writable enum macro that I wrote a few weeks back just for fun. Figured I could use it here, and that it might be helpful to have. Migrating existing enums is most likely impossible, however, because the lack of versioning in our serialization would mean we'd need to regenerate basically everything. Which, if someone wants to do, be my guess :P

**Review by markmeliaa — APPROVED** [review]

**Review by markmeliaa — APPROVED** [review]

**Comment by MarcGonzalezMoratona** [comment]
There are conflicting files 👀

**Review by Piterga12 — COMMENTED** [review]
Works great but there's conflicts on the filters

**Review by MarcGonzalezMoratona — DISMISSED** [review]

**Review by MarcGonzalezMoratona — APPROVED** [review]

**Review by Piterga12 — APPROVED** [review]
Good job!

**Pull request merged**
