### PR TITLE
fix: dash integration fixes

### PR DESCRIPTION
**Pull request by MarcGonzalezMoratona**
Improved the integration between the dash and attack animations.
Fix Allura's mass and gravity in gameplayTrial scene for Allura.
Fix Bix's state machine after a double jump, sometimes got stuck in double jump state
Add preInput to dash during jump or attack
Fix state machine to allow transitions between Dash and sorrounding states

### CODE REVIEW

**Review by markmeliaa — COMMENTED** [review]
Hey Marc, nice work! Just a couple changes:
- The issue that you last pr had that when the dash ends it briefly starts the running animation is happening again, after I dash, Bix is not set to completely idle and a frame of the running animation is played before being idle (it happened to me in the lvl 1 scene).
- And regarding the dash, now if I attack and press the dash key while attacking, the animation of the dash is never triggered but its functionality is, which looks weird as the player just gets pushed without any kind of visual feedback that a dash/roll has been performed.

**Comment by MarcGonzalezMoratona** [comment]
> * The issue that you last pr had that when the dash ends it briefly starts the running animation is happening again, after I dash, Bix is not set to completely idle and a frame of the running animation is played before being idle (it happened to me in the lvl 1 scene).

Hi Mark! Thank you for your feedback! I'll keep working on fixing this items you pointed out.

**Review by DADSILVER — APPROVED** [review]
Good Job, See fine for me. the only thing it was Mark said in the previous comment.

**Comment by markmeliaa** [comment]
Also, when Allura double jumps in her trial scene, she gets stucked in the attack animation, and neither her nor Bix are performing their jump attack no more when being in the air.

**Comment by MarcGonzalezMoratona** [comment]
> Also, when Allura double jumps in her trial scene, she gets stucked in the attack animation, and neither her nor Bix are performing their jump attack no more when being in the air.

Hi Mark! I tried to do my best to solve all you comments. Let me know if there's something missing!

**Comment by markmeliaa** [comment]
> And regarding the dash, now if I attack and press the dash key while attacking, the animation of the dash is never triggered but its functionality is, which looks weird as the player just gets pushed without any kind of visual feedback that a dash/roll has been performed.

The two other errors seem fixed, but this keeps happening for Bix in her trial scene and in the levels.

**Comment by Piterga12** [comment]
A really good job, just two things, first what Mark mentioned on the last comment and second, if you dash as soon as you land from a jump you try to dash, it dashes without doing the dash animation, i think it is because there is no conection on the state machine from landing to dashing

**Review by Piterga12 — COMMENTED** [review]
A really good job, just two things, first what Mark mentioned on the last comment and second, if you dash as soon as you land from a jump you try to dash, it dashes without doing the dash animation, i think it is because there is no conection on the state machine from landing to dashing

**Comment by MarcGonzalezMoratona** [comment]
> A really good job, just two things, first what Mark mentioned on the last comment and second, if you dash as soon as you land from a jump you try to dash, it dashes without doing the dash animation, i think it is because there is no conection on the state machine from landing to dashing

Thank you Peter! Nice catch! This kind of comments is what I really appreciate from your feedback, because it clearly shows how much effort you put on testing!

**Review by Piterga12 — COMMENTED** [review]
Two things, the first one isnt that important, but when i just stop moving, if i try to attack, it doesnt do the animation (shown on the first video).
And Second, more important, if after the first jump, you wait for the player to start falling a bit and do the second jump, it will do the walking animation, like if the player was detecting that is touching the ground (isGrounded), so apart from doing the walking animation in the air, as it detects you are in the ground, you can jump again and so go on (so basically if you get the timings right, you can jump infinitely (shown on the second video)


https://github.com/Horizons-Games/Axolotl-Engine/assets/80328187/68a5a482-1125-45b6-91e5-3a6648e4be0f

https://github.com/Horizons-Games/Axolotl-Engine/assets/80328187/13d6721d-eea5-4090-955e-f775caca9e15

**Pull request closed without merging**
