### PR TITLE
feat: improve spawn of the enemies

### PR DESCRIPTION
**Pull request by DADSILVER**
Now enemies spawn stay in the control room instead of in the area of the mini boss.

This PR can be tested on the scene _LEVEL02_ALFA.

This PR add:
- A path script that can be used to set a point that an enemy will follow.
- Now, the enemies can be paralyzed (different than stunned).
- activationLogicScript Work with enemies.
- Elevator work with enemies. And enemies wait for the elevator.

As you can see, there are files related to the final boss fight. This PR is not yet ready but we need this merge for the correct work of the ComponentAgent.

### CODE REVIEW

**Comment by markmeliaa** [comment]
Conflicts 👀

**Review by markmeliaa — COMMENTED** [review]
Code looks well, gj David!

**Review by Dedado3000 — APPROVED** [review]
Working perfectly but seems that you can easily acumulate enemies, no problem for this pr

**Review by diegusmejia117 — APPROVED** [review]

**Review by OriolSors — APPROVED** [review]
All the behavior of the spawning enemies matches perfectly with the elevator movement. Good job!!

**Review by Dedado3000 — APPROVED** [review]

**Pull request merged**
