### PR TITLE
feat: change uses of "enum" to "enum class"

### PR DESCRIPTION
**Pull request by markmeliaa**
ClickUp task: https://app.clickup.com/t/865br3ahk

I changed a couple enums from the camera/frustum stuff, so if someone from camera could take a look that will be nice!

### CODE REVIEW

**Comment by PaablooCH** [comment]
Task linked: [CU-865br3ahk Change uses of "enum" to "enum class"](https://app.clickup.com/t/865br3ahk)

**Review by gerard-queralt — APPROVED** [review]
Everything looks OK to me, thank you Mark! Let's see what our camera experts have to say ;)

**Review by OriolSors — APPROVED** [review]
For me it's okey the new use of the Enum class in order to avoid conflicts with integers. 

Thanks @markmeliaa!!

**Comment by OriolSors** [comment]
First it is needed to solve the conflict with ComponentCamera.h

image

**Comment by markmeliaa** [comment]
> First it is needed to solve the conflict with ComponentCamera.h

Done!

**Pull request merged**
