### PR TITLE
fix: multipliers camera boss

### PR DESCRIPTION
**Pull request by OriolSors**
Fixed camera multipliers not working.

### CODE REVIEW

**Review by markmeliaa — DISMISSED** [review]
Nice improvent, the boss fight looks better now!

**Comment by Dedado3000** [comment]
I Will convert this to draft because needs to put the multipliers and improve  when boss level is open

**Comment by markmeliaa** [comment]
> I Will convert this to draft because needs to put the multipliers and improve when boss level is open

Isn't the boss level available to be modified right now? In fact, in the list this pr is taking the scene hostage and there's people waiting.

**Review by Dedado3000 — APPROVED** [review]
Good Job with the work, i pushed the parameters to multiplier as we say

**Review by markmeliaa — APPROVED** [review]

**Pull request merged**
