### PR TITLE
feat: Missions on Level 1

### PR DESCRIPTION
**Pull request by Piterga12**
The missions are on the level 1, the mission stays visible for 30secs (this can be easily changed on the inspector) or when we enter on the trigger of the next mission (then the new mission appears and the old one leaves

### CODE REVIEW

**Review by Dedado3000 — APPROVED** [review]
Nice Work

**Review by Vlukkee — CHANGES_REQUESTED** [review]
Really nice job, need to made some changes

No timer in missions
Add 2 new mission hangar and cascade place.

**Review by Vlukkee — APPROVED** [review]
Amazing job!

**Review by markmeliaa — APPROVED** [review]
Great job Peter, congrats!

**Pull request merged**
