### PR TITLE
feat: Able to remove the selected gameobject from the hierachy with supr

### PR DESCRIPTION
**Pull request by totisama**

### CODE REVIEW

**Comment by markmeliaa** [comment]
Nice addition Rodrigo, but after the talk we had today in the discord #general chat I do not know if this should go directly to develop (eventhough it seems a pretty simple change), idk what @gerard-queralt has to say in this.

Regardless of that, I see this functionality working correctly (outside the known bugs regarding deleting gameobjects such as #173, #166 and so on).

**Comment by markmeliaa** [comment]
Maybe this could go to the `scenemanagement` branch and it will be merged with `develop` once its bug is fixed.

**Comment by Dedado3000** [comment]
LLevo 3 dias debugeando eliminando uno por uno los objetos de forma manual y ahora que he terminado me encuentro con esta pull request, necesito unas vacaciones urgentes

**Comment by gerard-queralt** [comment]
> Nice addition Rodrigo, but after the talk we had today in the discord #general chat I do not know if this should go directly to develop (eventhough it seems a pretty simple change), idk what @gerard-queralt has to say in this.

He actually asked me beforehand and I told him it was fine to point the MR to `develop`. As I understood it, what we agreed on on Discord was to use those intermediate branches when people are working on the same feature in different branches, like in `engine-mode`. Besides, this was branched from `develop` so merging into `scenemanagement` could create some issues.

**Comment by markmeliaa** [comment]
> He actually asked me beforehand and I told him it was fine to point the MR to `develop`. As I understood it, what we agreed on on Discord was to use those intermediate branches when people are working on the same feature in different branches, like in `engine-mode`. Besides, this was branched from `develop` so merging into `scenemanagement` could create some issues.
> 

Nice then!

**Review by markmeliaa — APPROVED** [review]

**Comment by totisama** [comment]
okay! ill check it out.

**Comment by PaablooCH** [comment]
> Thanks Rodrigo, as David said, this will certainly be really useful to have :P One thing I noticed is that this feature doesn't seem to work when moving through the hierarchy with the up and down arrows, could you have a look? Thanks!

It doesn't work because he delets the selected object, even if you move up and down with the arrows the selected object remains the same, we will need also to add a feature, that with the intro key, selects a new object, if we want a full interaction with imgui.

**Review by PaablooCH — APPROVED** [review]
Nice addition

**Comment by gerard-queralt** [comment]
> It doesn't work because he deletes the selected object, even if you move up and down with the arrows the selected object remains the same, we will need also to add a feature, that with the intro key, selects a new object, if we want a full interaction with imgui.

My bad, I thought we could change the selected GameObject with the arrow keys. Then this MR is perfect, I'll merge it.

**Review by gerard-queralt — APPROVED** [review]

**Pull request merged**
